### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Handsome1080P** [nuzayets/rawinput-debug#1]
I don't have installed NVIDIA Geforce software, only installed graphics driver.But still can't auto  turn off screen.Any solutions?

**Comment by nuzayets** [comment]
> I don't have installed NVIDIA Geforce software, only installed graphics driver.But still can't auto  turn off screen.Any solutions?

Try powercfg to see what is asking power manager to keep displays on. This is a common issue with many possible causes.

**Comment by Handsome1080P** [comment]
> > I don't have installed NVIDIA Geforce software, only installed graphics driver.But still can't auto  turn off screen.Any solutions?
> 
> Try powercfg to see what is asking power manager to keep displays on. This is a common issue with many possible causes.

Nothing shows in powercfg /requests.My system: Windows 10 least version 21H2.I try this solutions below:
1.Install latest Warthog Hotas official driver.Not working.
2.Enable/Disable USB/HID power management in Device Manager.Not working.
3.Set case power button depress to turn off screen.When I press the power button on the case, screen will turn off but it will turn on immediately.If I remove HOTAS, screen can turn off  continuously
